// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/15/2025, 1:24:07 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/christonomous/Coding/chrisberlin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/christonomous/Coding/chrisberlin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/christonomous/Coding/chrisberlin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/christonomous/Coding/chrisberlin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/christonomous/Coding/chrisberlin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/christonomous/Coding/chrisberlin/plugins/**/*.{js,ts,mjs}","/home/christonomous/Coding/chrisberlin/composables/**/*.{js,ts,mjs}","/home/christonomous/Coding/chrisberlin/utils/**/*.{js,ts,mjs}","/home/christonomous/Coding/chrisberlin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/christonomous/Coding/chrisberlin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/christonomous/Coding/chrisberlin/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;