
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AiDefiIntersectSection': typeof import("../components/AiDefiIntersectSection.vue")['default']
    'CookieConsent': typeof import("../components/CookieConsent.vue")['default']
    'Dashboard': typeof import("../components/Dashboard.vue")['default']
    'FAQSection': typeof import("../components/FAQSection.vue")['default']
    'FooterSection': typeof import("../components/FooterSection.vue")['default']
    'HeroSection': typeof import("../components/HeroSection.vue")['default']
    'JourneySection': typeof import("../components/JourneySection.vue")['default']
    'OfferSection': typeof import("../components/OfferSection.vue")['default']
    'PasswordProtection': typeof import("../components/PasswordProtection.vue")['default']
    'ReportsGrid': typeof import("../components/ReportsGrid.vue")['default']
    'ReportsSection': typeof import("../components/ReportsSection.vue")['default']
    'SocialLinks': typeof import("../components/SocialLinks.vue")['default']
    'TimelineSection': typeof import("../components/TimelineSection.vue")['default']
    'WorkHighlights': typeof import("../components/WorkHighlights.vue")['default']
    'ChatMessage': typeof import("../components/chat/ChatMessage.vue")['default']
    'ChatWidget': typeof import("../components/chat/ChatWidget.vue")['default']
    'TradingAboutSection': typeof import("../components/trading/AboutSection.vue")['default']
    'TradingCollaborationSection': typeof import("../components/trading/CollaborationSection.vue")['default']
    'TradingDifferentiatorsSection': typeof import("../components/trading/DifferentiatorsSection.vue")['default']
    'TradingFooterSection': typeof import("../components/trading/FooterSection.vue")['default']
    'TradingHeroSection': typeof import("../components/trading/HeroSection.vue")['default']
    'TradingPerformanceSection': typeof import("../components/trading/PerformanceSection.vue")['default']
    'TradingProjectsSection': typeof import("../components/trading/ProjectsSection.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAiDefiIntersectSection': typeof import("../components/AiDefiIntersectSection.vue")['default']
    'LazyCookieConsent': typeof import("../components/CookieConsent.vue")['default']
    'LazyDashboard': typeof import("../components/Dashboard.vue")['default']
    'LazyFAQSection': typeof import("../components/FAQSection.vue")['default']
    'LazyFooterSection': typeof import("../components/FooterSection.vue")['default']
    'LazyHeroSection': typeof import("../components/HeroSection.vue")['default']
    'LazyJourneySection': typeof import("../components/JourneySection.vue")['default']
    'LazyOfferSection': typeof import("../components/OfferSection.vue")['default']
    'LazyPasswordProtection': typeof import("../components/PasswordProtection.vue")['default']
    'LazyReportsGrid': typeof import("../components/ReportsGrid.vue")['default']
    'LazyReportsSection': typeof import("../components/ReportsSection.vue")['default']
    'LazySocialLinks': typeof import("../components/SocialLinks.vue")['default']
    'LazyTimelineSection': typeof import("../components/TimelineSection.vue")['default']
    'LazyWorkHighlights': typeof import("../components/WorkHighlights.vue")['default']
    'LazyChatMessage': typeof import("../components/chat/ChatMessage.vue")['default']
    'LazyChatWidget': typeof import("../components/chat/ChatWidget.vue")['default']
    'LazyTradingAboutSection': typeof import("../components/trading/AboutSection.vue")['default']
    'LazyTradingCollaborationSection': typeof import("../components/trading/CollaborationSection.vue")['default']
    'LazyTradingDifferentiatorsSection': typeof import("../components/trading/DifferentiatorsSection.vue")['default']
    'LazyTradingFooterSection': typeof import("../components/trading/FooterSection.vue")['default']
    'LazyTradingHeroSection': typeof import("../components/trading/HeroSection.vue")['default']
    'LazyTradingPerformanceSection': typeof import("../components/trading/PerformanceSection.vue")['default']
    'LazyTradingProjectsSection': typeof import("../components/trading/ProjectsSection.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AiDefiIntersectSection: typeof import("../components/AiDefiIntersectSection.vue")['default']
export const CookieConsent: typeof import("../components/CookieConsent.vue")['default']
export const Dashboard: typeof import("../components/Dashboard.vue")['default']
export const FAQSection: typeof import("../components/FAQSection.vue")['default']
export const FooterSection: typeof import("../components/FooterSection.vue")['default']
export const HeroSection: typeof import("../components/HeroSection.vue")['default']
export const JourneySection: typeof import("../components/JourneySection.vue")['default']
export const OfferSection: typeof import("../components/OfferSection.vue")['default']
export const PasswordProtection: typeof import("../components/PasswordProtection.vue")['default']
export const ReportsGrid: typeof import("../components/ReportsGrid.vue")['default']
export const ReportsSection: typeof import("../components/ReportsSection.vue")['default']
export const SocialLinks: typeof import("../components/SocialLinks.vue")['default']
export const TimelineSection: typeof import("../components/TimelineSection.vue")['default']
export const WorkHighlights: typeof import("../components/WorkHighlights.vue")['default']
export const ChatMessage: typeof import("../components/chat/ChatMessage.vue")['default']
export const ChatWidget: typeof import("../components/chat/ChatWidget.vue")['default']
export const TradingAboutSection: typeof import("../components/trading/AboutSection.vue")['default']
export const TradingCollaborationSection: typeof import("../components/trading/CollaborationSection.vue")['default']
export const TradingDifferentiatorsSection: typeof import("../components/trading/DifferentiatorsSection.vue")['default']
export const TradingFooterSection: typeof import("../components/trading/FooterSection.vue")['default']
export const TradingHeroSection: typeof import("../components/trading/HeroSection.vue")['default']
export const TradingPerformanceSection: typeof import("../components/trading/PerformanceSection.vue")['default']
export const TradingProjectsSection: typeof import("../components/trading/ProjectsSection.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAiDefiIntersectSection: typeof import("../components/AiDefiIntersectSection.vue")['default']
export const LazyCookieConsent: typeof import("../components/CookieConsent.vue")['default']
export const LazyDashboard: typeof import("../components/Dashboard.vue")['default']
export const LazyFAQSection: typeof import("../components/FAQSection.vue")['default']
export const LazyFooterSection: typeof import("../components/FooterSection.vue")['default']
export const LazyHeroSection: typeof import("../components/HeroSection.vue")['default']
export const LazyJourneySection: typeof import("../components/JourneySection.vue")['default']
export const LazyOfferSection: typeof import("../components/OfferSection.vue")['default']
export const LazyPasswordProtection: typeof import("../components/PasswordProtection.vue")['default']
export const LazyReportsGrid: typeof import("../components/ReportsGrid.vue")['default']
export const LazyReportsSection: typeof import("../components/ReportsSection.vue")['default']
export const LazySocialLinks: typeof import("../components/SocialLinks.vue")['default']
export const LazyTimelineSection: typeof import("../components/TimelineSection.vue")['default']
export const LazyWorkHighlights: typeof import("../components/WorkHighlights.vue")['default']
export const LazyChatMessage: typeof import("../components/chat/ChatMessage.vue")['default']
export const LazyChatWidget: typeof import("../components/chat/ChatWidget.vue")['default']
export const LazyTradingAboutSection: typeof import("../components/trading/AboutSection.vue")['default']
export const LazyTradingCollaborationSection: typeof import("../components/trading/CollaborationSection.vue")['default']
export const LazyTradingDifferentiatorsSection: typeof import("../components/trading/DifferentiatorsSection.vue")['default']
export const LazyTradingFooterSection: typeof import("../components/trading/FooterSection.vue")['default']
export const LazyTradingHeroSection: typeof import("../components/trading/HeroSection.vue")['default']
export const LazyTradingPerformanceSection: typeof import("../components/trading/PerformanceSection.vue")['default']
export const LazyTradingProjectsSection: typeof import("../components/trading/ProjectsSection.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
